theme: jekyll-theme-minimal
title: Malika Butzbach
description: journaliste multimédias, Paris <br> Portable : 0675987151 <br> mail : malika.butzbach@gmail.com <br> 11 rue Georgette Rostaing 94 200 Ivry-s/-Seine <br> Née le 18/09/1994 
logo: /images/logo.jpeg
